### PR TITLE
Always calculate TDD

### PR DESCRIPTION
**Pull request by simonp22**
This PR is in response to https://github.com/nightscout/Trio/issues/393. 

At the moment just a proposed solution up for discussion in https://github.com/nightscout/Trio/issues/393

### CODE REVIEW

**Comment by mountrcg** [comment]
this is fine and tested

**Comment by mountrcg** [comment]
hold that thought for a moment

> @simonp22 could you close this and reopen with target branch being tcd please? Please also adjust line https://github.com/nightscout/trio-oref/blob/06ca64b5355d40c44cd41dd4cc85a31c81389edd/lib/determine-basal/determine-basal.js#L644 to `weightedAverage > 1`

**Comment by bjornoleh** [comment]
I changed the base branch to tcd. Please check if this looks good. @mountrcg

**Comment by simonp22** [comment]
> hold that thought for a moment
> 
> > @simonp22 could you close this and reopen with target branch being tcd please? Please also adjust line https://github.com/nightscout/trio-oref/blob/06ca64b5355d40c44cd41dd4cc85a31c81389edd/lib/determine-basal/determine-basal.js#L644
> >  to `weightedAverage > 1`

Could there not be scenarios where weightedAverage < 1 here? Is it safe to ignore those?

**Comment by mountrcg** [comment]
@simonp22 `weightedAverage` is a TDD value and one of the fault catches in dynISF sets that value to 1. I do not think anyone will ever have a TDD of 1 or smaller. So in order not to have that fault catch populate a TDD = 1, I suggest the quickfix to make it `>1`

**Comment by mountrcg** [comment]
unfortunatly the crew voted to not release this for Trio 0.2.x or whatnot, so it will come with 1.0

**Comment by simonp22** [comment]
Changes now made

**Pull request merged**
